#!/usr/bin/env bash
set -e

case "$1" in
"") echo "usage: q <command> [<args>]

Some useful q commands are:
   commands      List all q commands

See 'q help <command>' for information on a specific command."
;;
# >>>>> copy from this block to add more help blocks!
# See https://github.com/sstephenson/rbenv/blob/master/libexec/rbenv-help for more examples.
commands) echo "usage: q commands
       q commands --sh
       q commands --no-sh

List all q commands."
;;
# >>>>>
*)
  command_path="$(command -v "q-$1" || true)"
  if [ -n "$command_path" ]; then
    echo "Sorry, the \`$1' command isn't documented yet."
    echo
    echo "You can view the command's source here:"
    echo "$command_path"
    echo
  else
    echo "q: no such command \`$1'"
  fi
esac
