#!/usr/bin/env bash
set -e

print=""
if [ "$1" = "-" ]; then
  print=1
  shift
fi

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshenv'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load q automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo "eval \"\$(${_Q_ROOT}/bin/q init -)\""
    echo
  } >&2

  exit 1
fi

echo "export PATH=\"\${PATH}:${_Q_ROOT}/bin\""

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/q.${shell}\""
  ;;
esac
